#########################################################
# ClickMobs Settings
# NOTE: RELOAD/RESTART SERVER FOR CHANGES TO TAKE EFFECT
#########################################################
config-version: 3
#########################################################

# Language of the plugin.
# Currently supported languages: en_US, de_DE
language: en_US

# Whether to check for updates on server startup.
# Strongly Recommended.
check-update: true

# Whether to have specific permissions for each mob.
# For example, players won't be able to pick up a creeper unless they have
# both "clickmobs.pickup" and "clickmobs.pickup.creeper" permissions.
# - Whitelisted mobs will still be able to be picked up without a mob-specific permission.
# - Blacklisted mobs will not be able to be picked up even with a mob-specific permission.
# Default: false
per-mob-permissions: false

# Whether to allow hostile mobs to be picked up.
# You can override this setting for individual mobs in the "whitelisted-mobs" list.
# Default: false
allow-hostile: false

# Whether to ONLY allow mobs that are whitelisted to be picked up.
# WARNING: This will override the "allow-hostile" setting.
# Default: false
only-allow-whitelisted: false

# List of mobs that are allowed to be picked up.
# Entries must be uppercase.
# Default: [ ]
whitelisted-mobs: [ ]

# List of mobs to blacklist from being picked up.
# Entries must be uppercase.
blacklisted-mobs:
  - ENDER_DRAGON
  - WITHER

# Set a custom model data for the picked up mobs.
# This is useful for resource packs that want to change the model/texture of picked up mobs.
# Example:
# custom-model-data:
#   creeper: 10
#   skeleton: 11
custom-model-data: