#########################################################
# ClickMobs Settings
# NOTE: RELOAD/RESTART SERVER FOR CHANGES TO TAKE EFFECT
#########################################################
config-version: 1
#########################################################

# Language of the plugin.
# Currently supported languages: en_US, de_DE
language: en_US

# Whether to check for updates on server startup.
# Strongly Recommended.
check-update: true

# Whether to allow hostile mobs to be picked up.
# You can override this setting for individual mobs in the "whitelisted-mobs" list.
# Default: false
allow-hostile: false

# Whether to ONLY allow mobs that are whitelisted to be picked up.
# WARNING: This will override the "allow-hostile" setting.
# Default: false
only-allow-whitelisted: false

# List of mobs that are allowed to be picked up.
# Default: [ ]
whitelisted-mobs: [ ]

# List of mobs to blacklist from being picked up.
blacklisted-mobs:
  - ENDER_DRAGON
  - WITHER