#########################################################
# ClickMobs Settings
# NOTE: RELOAD/RESTART SERVER FOR CHANGES TO TAKE EFFECT
#########################################################
config-version: 1
#########################################################

# Language of the plugin.
# Currently supported languages: en_US, de_DE
language: en_US

# Whether to check for updates on server startup.
# Strongly Recommended.
check-update: true

whitelisted-mobs: [ ]
blacklisted-mobs:
  - ENDER_DRAGON
  - WITHER